### ISSUE TITLE
Problem installing the package

### ISSUE THREAD

**Issue by gdistiller** [edzer/sp#25]
Hi
I hope this is the right forum to try and get some help related to problems installing the sp package on more recent versions of R. I am getting the following error:

* installing *source* package ‘sp’ ...
** package ‘sp’ successfully unpacked and MD5 sums checked
** libs
gcc -I/opt/exp_soft/R-3.3.2/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -I/opt/exp_soft/libraries/R-compile-lib-suite/packages/include  -c Rcentroid.c -o Rcentroid.o
gcc -I/opt/exp_soft/R-3.3.2/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -I/opt/exp_soft/libraries/R-compile-lib-suite/packages/include  -c gcdist.c -o gcdist.o
gcc -I/opt/exp_soft/R-3.3.2/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -I/opt/exp_soft/libraries/R-compile-lib-suite/packages/include  -c init.c -o init.o
gcc -I/opt/exp_soft/R-3.3.2/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -I/opt/exp_soft/libraries/R-compile-lib-suite/packages/include  -c pip.c -o pip.o
gcc -I/opt/exp_soft/R-3.3.2/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -I/opt/exp_soft/libraries/R-compile-lib-suite/packages/include  -c pip2.c -o pip2.o
gcc -I/opt/exp_soft/R-3.3.2/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -I/opt/exp_soft/libraries/R-compile-lib-suite/packages/include  -c sp_xports.c -o sp_xports.o
gcc -I/opt/exp_soft/R-3.3.2/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -I/opt/exp_soft/libraries/R-compile-lib-suite/packages/include  -c surfaceArea.c -o surfaceArea.o
surfaceArea.c: In function ‘sarea’:
surfaceArea.c:66: error: ‘for’ loop initial declaration used outside C99 mode
surfaceArea.c:67: error: ‘for’ loop initial declaration used outside C99 mode
surfaceArea.c:71: error: ‘for’ loop initial declaration used outside C99 mode
make: *** [surfaceArea.o] Error 1
ERROR: compilation failed for package ‘sp’
* removing ‘/home/gdistiller/R/x86_64-pc-linux-gnu-library/3.3/sp’

I have no idea what could be causing the surfaceArea error message. Any advice would be much appreciated.

Thanks

Greg

**Comment by edzer** [comment]
You didn't say which command you used to install the package. None of the 13 [CRAN flavours](https://cran.r-project.org/web/checks/check_results_sp.html) have such troubles; maybe also worth reading [Writing R extension](https://cran.r-project.org/doc/manuals/R-exts.html)?

**Comment by gdistiller** [comment]
Hi and thanks so much for the quick reply. I just ran the install.packages() command. What I didn’t say is that I am trying to get something running on a cluster and so I am using putty to access the server and then trying to install sp there. On my own desktop I have managed to install the package under R version 3.3.1, but I can see that the version I have there is 1.2.3 so not sure if it has something to do with the latest version? Do you think it could be something related to the cluster architecture? The install works on an earlier version of R (3.2.0) so I’m really not sure what is going on…

**Comment by edzer** [comment]
If I install it (on ubuntu), I see, for this file:
```
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c surfaceArea.c -o surfaceArea.o
```
and that looks pretty different. Why does yours not use `-std=gnu99`?

**Comment by gdistiller** [comment]
Edzer I’m sorry but I have no idea. I am a R user and write functions etc but do not really understand the underlying technical bits of the installation. To be honest I don’t have any idea what you are talking about. I can try enlist the help of the technician that maintains the cluster but I know that he is not familiar with R and so will probably not be of much help. Do you think it can have anything to do with the location of the library?

**Comment by edzer** [comment]
No.

**Comment by gdistiller** [comment]
OK so are you saying that you have no idea why the installation is failing?

**Comment by edzer** [comment]
No, I just said that I do not think it has to do with the custom directory; to give advice, I'd have to know what kind of computer architecture you're working on (operating system, versions), which compilers it runs (and versions), which R version and how that was installed, to start with, but even with that knowledge I'm not sure I could give you advice.

**Comment by gdistiller** [comment]
Ok, well I’ve got it working on a different (earlier) version of R so I’m not sure it will then be worth the time trying to figure this out. Plus I would need to get the technician involved as I have little to no understanding of the architecture, and I have no idea of his willingness to try sort it out.

Thanks again for your quick replies…

Greg
